Repository ISIS3510-202410-Team5/Flutter, pull requests merged in 2024-04, with the labels that each got.

#14 cambio proyecto de firebase
  unimarket/.vscode/settings.json
  unimarket/android/app/build.gradle
  unimarket/android/app/google-services.json
  unimarket/android/settings.gradle
  unimarket/firebase.json
  unimarket/lib/firebase_options.dart
Labels: Sprint 2

#19 MVC Pattern Implementation
  unimarket/lib/Controllers/auth_controller.dart
  unimarket/lib/Controllers/home_controller.dart
  unimarket/lib/Controllers/productDetail_controller.dart
  unimarket/lib/Controllers/publish_controller.dart
  unimarket/lib/Controllers/search_controller.dart
  unimarket/lib/Models/productDetail_model.dart
  unimarket/lib/Models/product_model.dart
  unimarket/lib/Models/productos.dart
  unimarket/lib/Models/seller_model.dart
  unimarket/lib/Models/user_model.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/Views/login_view.dart
  unimarket/lib/Views/productDetail_view.dart
  unimarket/lib/Views/publish_view.dart
  unimarket/lib/Views/register_view.dart
  unimarket/lib/Views/search_view.dart
  unimarket/lib/main.dart
  unimarket/lib/modelo/usuario.dart
  unimarket/macos/Flutter/GeneratedPluginRegistrant.swift
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
  unimarket/windows/flutter/generated_plugin_registrant.cc
  unimarket/windows/flutter/generated_plugins.cmake
Labels: enhancement

#21 Context Aware Feature Implemented
  unimarket/lib/Controllers/publish_controller.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/Views/publish_view.dart
  unimarket/lib/main.dart
  unimarket/lib/theme.dart
  unimarket/macos/Flutter/GeneratedPluginRegistrant.swift
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
Labels: enhancement

#23 16 get the products from beckend database
  unimarket/lib/Controllers/auth_controller.dart
  unimarket/lib/Controllers/home_controller.dart
  unimarket/lib/Controllers/publish_controller.dart
  unimarket/lib/Controllers/search_controller.dart
  unimarket/lib/Controllers/search_controllerUnimarket.dart
  unimarket/lib/Models/Repository/productReposirory.dart
  unimarket/lib/Models/model.dart
  unimarket/lib/Models/productDetail_model.dart
  unimarket/lib/Models/product_model.dart
  unimarket/lib/Models/productos.dart
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/chat_view.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/Views/login_view.dart
  unimarket/lib/Views/productDetail_view.dart
  unimarket/lib/Views/publish_view.dart
  unimarket/lib/Views/register_view.dart
  unimarket/lib/Views/search_view.dart
  unimarket/lib/main.dart
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
Labels: Sprint 2

#25 24 implement cart view and its logic
  unimarket/lib/Controllers/auth_controller.dart
  unimarket/lib/Controllers/cart_controller.dart
  unimarket/lib/Controllers/productDetail_controller.dart
  unimarket/lib/Models/Repository/cartRepository.dart
  unimarket/lib/Models/Repository/productReposirory.dart
  unimarket/lib/Models/model.dart
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/cart_view.dart
  unimarket/lib/Views/chat_view.dart
  unimarket/lib/Views/login_view.dart
Labels: Sprint 2

#27 22 to implement the eventual connectivity in the search view
  unimarket/lib/Controllers/search_controllerUnimarket.dart
  unimarket/lib/Models/Repository/productReposirory.dart
  unimarket/lib/Models/model.dart
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/Views/login_view.dart
  unimarket/lib/Views/search_view.dart
  unimarket/lib/main.dart
  unimarket/lib/nav_bar.dart
  unimarket/lib/resources/connectivity_service.dart
  unimarket/lib/theme.dart
  unimarket/macos/Flutter/GeneratedPluginRegistrant.swift
  unimarket/pubspec.lock
  unimarket/pubspec.yaml
  unimarket/windows/flutter/generated_plugin_registrant.cc
  unimarket/windows/flutter/generated_plugins.cmake
Labels: Sprint 3

#29 Eventual Connectivity Implemented
  unimarket/lib/Views/body_view.dart
  unimarket/lib/Views/home_view.dart
  unimarket/lib/main.dart
Labels: Sprint 3
